# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_embed.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11video_embed.proto\x12\x0bvideo_embed\"5\n\x11VideoEmbedRequest\x12\x11\n\tvideo_url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"H\n\x12VideoEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2i\n\x11VideoEmbedService\x12T\n\x11GetVideoEmbedding\x12\x1e.video_embed.VideoEmbedRequest\x1a\x1f.video_embed.VideoEmbedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_embed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOEMBEDREQUEST']._serialized_start=34
  _globals['_VIDEOEMBEDREQUEST']._serialized_end=87
  _globals['_VIDEOEMBEDRESPONSE']._serialized_start=89
  _globals['_VIDEOEMBEDRESPONSE']._serialized_end=161
  _globals['_VIDEOEMBEDSERVICE']._serialized_start=163
  _globals['_VIDEOEMBEDSERVICE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
