# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_embed_pb2 as video__embed__pb2


class VideoEmbedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideoEmbedding = channel.unary_unary(
                '/video_embed.VideoEmbedService/GetVideoEmbedding',
                request_serializer=video__embed__pb2.VideoEmbedRequest.SerializeToString,
                response_deserializer=video__embed__pb2.VideoEmbedResponse.FromString,
                )


class VideoEmbedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVideoEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoEmbedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideoEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoEmbedding,
                    request_deserializer=video__embed__pb2.VideoEmbedRequest.FromString,
                    response_serializer=video__embed__pb2.VideoEmbedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'video_embed.VideoEmbedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoEmbedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVideoEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/video_embed.VideoEmbedService/GetVideoEmbedding',
            video__embed__pb2.VideoEmbedRequest.SerializeToString,
            video__embed__pb2.VideoEmbedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
