spring:
  jmx:
    enabled: false
  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 50   # Lettuce 连接池最大连接数（建议比 Jedis 小很多）
          max-idle: 20
          min-idle: 5
          max-wait: 1000ms
          time-between-eviction-runs: 30s

  # Kafka（关键修复点）
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    consumer:
      group-id: v-omni-auth-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/omni_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ${V_OMNI_DATASOURCE_PASSWORD}
#    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 10
#      idle-timeout: 30000
#      connection-timeout: 20000

  # Mail
  mail:
    host: smtp.qq.com
    port: 465
    username: ${V_OMNI_MAIL_USERNAME}
    password: ${V_OMNI_MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true