spring:
  profiles:
    active: dev  # 默认激活开发环境配置
  application:
    name: v-omni-auth

  # Jackson 全局配置：处理前后端交互的时间格式和空值
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null # 字段为 null 时不返回给前端，节省带宽

  threads:
    virtual:
      enabled: true

server:
  port: 18281

v-omni:
  auth:
    jwt-secret: ${V_OMNI_JWT_SECRET}

