# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vomni.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vomni.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvomni.proto\x12\x05vomni\"6\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x03(\x0c\x12\x12\n\ndo_pooling\x18\x02 \x01(\x08\"\x8b\x01\n\x10RecommendRequest\x12!\n\nq_5_videos\x18\x01 \x03(\x0b\x32\r.vomni.Vector\x12\x1e\n\x07short_k\x18\x02 \x03(\x0b\x32\r.vomni.Vector\x12\x1d\n\x06long_k\x18\x03 \x03(\x0b\x32\r.vomni.Vector\x12\x15\n\rshort_weights\x18\x04 \x03(\x02\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\";\n\x11RecommendResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0euser_embedding\x18\x02 \x03(\x02\" \n\x0eVectorResponse\x12\x0e\n\x06values\x18\x01 \x03(\x02\"5\n\x13MultiVectorResponse\x12\x1e\n\x07vectors\x18\x01 \x03(\x0b\x32\r.vomni.Vector2\xda\x01\n\x0bRecommender\x12\x45\n\x10GetUserEmbedding\x12\x17.vomni.RecommendRequest\x1a\x18.vomni.RecommendResponse\x12\x45\n\x12GetImageEmbeddings\x12\x13.vomni.ImageRequest\x1a\x1a.vomni.MultiVectorResponse\x12=\n\x10GetTextEmbedding\x12\x12.vomni.TextRequest\x1a\x15.vomni.VectorResponseB\x12\n\x0e\x63om.vomni.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vomni_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.vomni.grpcP\001'
  _globals['_IMAGEREQUEST']._serialized_start=22
  _globals['_IMAGEREQUEST']._serialized_end=76
  _globals['_RECOMMENDREQUEST']._serialized_start=79
  _globals['_RECOMMENDREQUEST']._serialized_end=218
  _globals['_TEXTREQUEST']._serialized_start=220
  _globals['_TEXTREQUEST']._serialized_end=247
  _globals['_VECTOR']._serialized_start=249
  _globals['_VECTOR']._serialized_end=273
  _globals['_RECOMMENDRESPONSE']._serialized_start=275
  _globals['_RECOMMENDRESPONSE']._serialized_end=334
  _globals['_VECTORRESPONSE']._serialized_start=336
  _globals['_VECTORRESPONSE']._serialized_end=368
  _globals['_MULTIVECTORRESPONSE']._serialized_start=370
  _globals['_MULTIVECTORRESPONSE']._serialized_end=423
  _globals['_RECOMMENDER']._serialized_start=426
  _globals['_RECOMMENDER']._serialized_end=644
# @@protoc_insertion_point(module_scope)
