# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vomni_pb2 as vomni__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vomni_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserEmbedding = channel.unary_unary(
                '/vomni.Recommender/GetUserEmbedding',
                request_serializer=vomni__pb2.RecommendRequest.SerializeToString,
                response_deserializer=vomni__pb2.RecommendResponse.FromString,
                _registered_method=True)
        self.GetImageEmbeddings = channel.unary_unary(
                '/vomni.Recommender/GetImageEmbeddings',
                request_serializer=vomni__pb2.ImageRequest.SerializeToString,
                response_deserializer=vomni__pb2.MultiVectorResponse.FromString,
                _registered_method=True)
        self.GetTextEmbedding = channel.unary_unary(
                '/vomni.Recommender/GetTextEmbedding',
                request_serializer=vomni__pb2.TextRequest.SerializeToString,
                response_deserializer=vomni__pb2.VectorResponse.FromString,
                _registered_method=True)


class RecommenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImageEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTextEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserEmbedding,
                    request_deserializer=vomni__pb2.RecommendRequest.FromString,
                    response_serializer=vomni__pb2.RecommendResponse.SerializeToString,
            ),
            'GetImageEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageEmbeddings,
                    request_deserializer=vomni__pb2.ImageRequest.FromString,
                    response_serializer=vomni__pb2.MultiVectorResponse.SerializeToString,
            ),
            'GetTextEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTextEmbedding,
                    request_deserializer=vomni__pb2.TextRequest.FromString,
                    response_serializer=vomni__pb2.VectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vomni.Recommender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vomni.Recommender', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Recommender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vomni.Recommender/GetUserEmbedding',
            vomni__pb2.RecommendRequest.SerializeToString,
            vomni__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImageEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vomni.Recommender/GetImageEmbeddings',
            vomni__pb2.ImageRequest.SerializeToString,
            vomni__pb2.MultiVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTextEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vomni.Recommender/GetTextEmbedding',
            vomni__pb2.TextRequest.SerializeToString,
            vomni__pb2.VectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
