spring:

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 50   # Lettuce 连接池最大连接数（建议比 Jedis 小很多）
          max-idle: 20
          min-idle: 5
          max-wait: 1000ms
          time-between-eviction-runs: 30s
      password: ${V_OMNI_REDIS_PASSWORD}
      username: ${V_OMNI_REDIS_USERNAME}

  # Kafka（关键修复点）
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
    consumer:
      group-id: v-omni-search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/omni_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ${V_OMNI_DATASOURCE_PASSWORD}

  elasticsearch:
    uris: http://localhost:19200

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: ${V_OMNI_MINIO_PASSWORD}
  bucket-name: v-omni-bucket      # 刚刚创建的存储桶名称
  upload-url-expiry-seconds: 7200

  bucket:
    final-video: final-video